#include "WasmApiHeader.h"

#include "model/NodeClass.h"

#include <fstream>

static bool IsCIdentifier(const std::string& name)
{
    if (name.empty()) {
        return false;
    }
    for (std::size_t i = 0; i < name.size(); ++i) {
        const char c = name[i];
        const bool alpha = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_';
        const bool digit = (c >= '0' && c <= '9');
        if (!(alpha || (i > 0 && digit))) {
            return false;
        }
    }
    return true;
}

static bool IsStructField(const PropertyDef& def)
{
    return def.container == PropertyContainer::None
        && (def.type == PinType::Float || def.type == PinType::Int
            || def.type == PinType::Bool);
}

static const char* FieldCType(PinType type)
{
    switch (type) {
    case PinType::Float:
        return "float";
    case PinType::Int:
        return "int";
    case PinType::Bool:
        return "bool";
    default:
        return "int";
    }
}

// True for classes that read as plain data records: identifier name and
// one or more scalar numeric/bool properties with identifier names.
static bool IsDataCarrierClass(const NodeClass& nodeClass)
{
    if (!IsCIdentifier(nodeClass.GetName())) {
        return false;
    }
    const std::vector<PropertyDef>& properties = nodeClass.GetProperties();
    if (properties.empty()) {
        return false;
    }
    for (const PropertyDef& def : properties) {
        if (!IsStructField(def) || !IsCIdentifier(def.name)) {
            return false;
        }
    }
    return true;
}

static void WriteReadCall(std::ofstream& file, const PropertyDef& def, int fieldIndex)
{
    switch (def.type) {
    case PinType::Float:
        file << "    value." << def.name << " = static_cast<float>(gau_input_f64(baseIndex + "
             << fieldIndex << "));\n";
        break;
    case PinType::Int:
        file << "    value." << def.name << " = gau_input_i32(baseIndex + "
             << fieldIndex << ");\n";
        break;
    case PinType::Bool:
        file << "    value." << def.name << " = gau_input_bool(baseIndex + "
             << fieldIndex << ") != 0;\n";
        break;
    default:
        break;
    }
}

static void WriteWriteCall(std::ofstream& file, const PropertyDef& def, int fieldIndex)
{
    switch (def.type) {
    case PinType::Float:
        file << "    gau_output_f64(baseIndex + " << fieldIndex
             << ", static_cast<double>(value." << def.name << "));\n";
        break;
    case PinType::Int:
        file << "    gau_output_i32(baseIndex + " << fieldIndex
             << ", value." << def.name << ");\n";
        break;
    case PinType::Bool:
        file << "    gau_output_bool(baseIndex + " << fieldIndex
             << ", value." << def.name << " ? 1 : 0);\n";
        break;
    default:
        break;
    }
}

bool WriteWasmApiHeader(const std::string& path, std::string& outError)
{
    std::ofstream file(path, std::ios::binary);
    if (!file.is_open()) {
        outError = "cannot write " + path;
        return false;
    }

    file << "// Auto-generated by GAU from the node class registry.\n"
            "// Regenerated on every wasm build - do not edit.\n"
            "#pragma once\n"
            "\n"
            "extern \"C\" {\n"
            "int    gau_input_i32(int index);\n"
            "double gau_input_f64(int index);\n"
            "int    gau_input_bool(int index);\n"
            "int    gau_input_str(int index, char* buffer, int capacity);\n"
            "int    gau_property_i32(int index);\n"
            "double gau_property_f64(int index);\n"
            "int    gau_property_str(int index, char* buffer, int capacity);\n"
            "void   gau_output_i32(int index, int value);\n"
            "void   gau_output_f64(int index, double value);\n"
            "void   gau_output_bool(int index, int value);\n"
            "void   gau_output_str(int index, const char* text, int length);\n"
            "void   gau_exec(int outputIndex);\n"
            "void   gau_log(const char* text, int length);\n"
            "}\n";

    for (const NodeClass* nodeClass : NodeClass::GetRegistry()) {
        if (!IsDataCarrierClass(*nodeClass)) {
            continue;
        }
        const std::vector<PropertyDef>& properties = nodeClass->GetProperties();
        const char* name = nodeClass->GetName();

        file << "\nstruct " << name << "\n{\n";
        for (const PropertyDef& def : properties) {
            file << "    " << FieldCType(def.type) << " " << def.name << ";\n";
        }
        file << "};\n";

        file << "\n// Reads " << properties.size()
             << " consecutive input pins starting at baseIndex.\n";
        file << "inline " << name << " gau_read_" << name << "(int baseIndex)\n{\n";
        file << "    " << name << " value;\n";
        for (int i = 0; i < static_cast<int>(properties.size()); ++i) {
            WriteReadCall(file, properties[static_cast<std::size_t>(i)], i);
        }
        file << "    return value;\n}\n";

        file << "\n// Writes " << properties.size()
             << " consecutive output pins starting at baseIndex.\n";
        file << "inline void gau_write_" << name << "(int baseIndex, const " << name
             << "& value)\n{\n";
        for (int i = 0; i < static_cast<int>(properties.size()); ++i) {
            WriteWriteCall(file, properties[static_cast<std::size_t>(i)], i);
        }
        file << "}\n";
    }

    return file.good();
}
