// Auto-generated by GAU from the node class registry.
// Regenerated on every wasm build - do not edit.
#pragma once

extern "C" {
int    gau_input_i32(int index);
double gau_input_f64(int index);
int    gau_input_bool(int index);
int    gau_input_str(int index, char* buffer, int capacity);
int    gau_property_i32(int index);
double gau_property_f64(int index);
int    gau_property_str(int index, char* buffer, int capacity);
void   gau_output_i32(int index, int value);
void   gau_output_f64(int index, double value);
void   gau_output_bool(int index, int value);
void   gau_output_str(int index, const char* text, int length);
void   gau_exec(int outputIndex);
void   gau_log(const char* text, int length);
}

struct Vector3f
{
    float x;
    float y;
    float z;
};

// Reads 3 consecutive input pins starting at baseIndex.
inline Vector3f gau_read_Vector3f(int baseIndex)
{
    Vector3f value;
    value.x = static_cast<float>(gau_input_f64(baseIndex + 0));
    value.y = static_cast<float>(gau_input_f64(baseIndex + 1));
    value.z = static_cast<float>(gau_input_f64(baseIndex + 2));
    return value;
}

// Writes 3 consecutive output pins starting at baseIndex.
inline void gau_write_Vector3f(int baseIndex, const Vector3f& value)
{
    gau_output_f64(baseIndex + 0, static_cast<double>(value.x));
    gau_output_f64(baseIndex + 1, static_cast<double>(value.y));
    gau_output_f64(baseIndex + 2, static_cast<double>(value.z));
}
