// Auto-generated by GAU from the node class registry.
// Regenerated on every wasm build - do not edit.
#pragma once

extern "C" {
int    gau_input_i32(int index);
double gau_input_f64(int index);
int    gau_input_bool(int index);
int    gau_input_str(int index, char* buffer, int capacity);
int    gau_property_i32(int index);
double gau_property_f64(int index);
int    gau_property_str(int index, char* buffer, int capacity);
void   gau_output_i32(int index, int value);
void   gau_output_f64(int index, double value);
void   gau_output_bool(int index, int value);
void   gau_output_str(int index, const char* text, int length);
void   gau_exec(int outputIndex);
void   gau_log(const char* text, int length);
}

// --- Text helpers -------------------------------------------------
// Wasm functions build freestanding (-nostdlib): <iostream>,
// <string>, snprintf etc. are unavailable. Build text in a GauStr
// and hand it to an output pin or the log:
//
//   GauStr s = gau_str("{");
//   gau_append(s, v.x);        // float/double, 2 fraction digits
//   gau_append(s, ", ");
//   gau_append(s, 42);         // int/long
//   gau_append(s, '}');
//   gau_output_str(0, s);

struct GauStr
{
    char data[512];
    int len;
};

inline GauStr gau_str(const char* text = "")
{
    GauStr s;
    s.len = 0;
    while (text[s.len] != 0 && s.len < 511) {
        s.data[s.len] = text[s.len];
        ++s.len;
    }
    s.data[s.len] = 0;
    return s;
}

inline GauStr& gau_append(GauStr& s, char c)
{
    if (s.len < 511) {
        s.data[s.len] = c;
        ++s.len;
        s.data[s.len] = 0;
    }
    return s;
}

inline GauStr& gau_append(GauStr& s, const char* text)
{
    while (*text != 0) {
        gau_append(s, *text);
        ++text;
    }
    return s;
}

inline GauStr& gau_append(GauStr& s, long value)
{
    unsigned long u;
    if (value < 0) {
        gau_append(s, '-');
        u = static_cast<unsigned long>(-(value + 1)) + 1ul;
    } else {
        u = static_cast<unsigned long>(value);
    }
    char digits[20];
    int count = 0;
    do {
        digits[count] = static_cast<char>('0' + u % 10ul);
        ++count;
        u /= 10ul;
    } while (u != 0ul);
    while (count > 0) {
        --count;
        gau_append(s, digits[count]);
    }
    return s;
}

inline GauStr& gau_append(GauStr& s, int value)
{
    return gau_append(s, static_cast<long>(value));
}

inline GauStr& gau_append(GauStr& s, double value, int decimals = 2)
{
    if (value < 0.0) {
        gau_append(s, '-');
        value = -value;
    }
    double scale = 1.0;
    for (int i = 0; i < decimals; ++i) {
        scale *= 10.0;
    }
    value += 0.5 / scale;
    unsigned long ip = static_cast<unsigned long>(value);
    gau_append(s, static_cast<long>(ip));
    if (decimals > 0) {
        gau_append(s, '.');
        double frac = value - static_cast<double>(ip);
        for (int i = 0; i < decimals; ++i) {
            frac *= 10.0;
            int digit = static_cast<int>(frac);
            if (digit > 9) {
                digit = 9;
            }
            frac -= static_cast<double>(digit);
            gau_append(s, static_cast<char>('0' + digit));
        }
    }
    return s;
}

inline void gau_output_str(int index, const GauStr& s)
{
    gau_output_str(index, s.data, s.len);
}

inline void gau_log(const GauStr& s)
{
    gau_log(s.data, s.len);
}

// String is the value type for typed function signatures: build
// one by concatenation and return it, e.g.
//   extern "C" String Format(const Vector3f& v)
//   { return ftoa(v.x) + ", " + ftoa(v.y) + ", " + ftoa(v.z); }
typedef GauStr String;

inline GauStr operator+(GauStr a, const GauStr& b)
{
    for (int i = 0; i < b.len; ++i) {
        gau_append(a, b.data[i]);
    }
    return a;
}

inline GauStr operator+(GauStr a, const char* b)
{
    gau_append(a, b);
    return a;
}

inline GauStr operator+(const char* a, const GauStr& b)
{
    GauStr s = gau_str(a);
    return s + b;
}

// Decimal text of a float value (default two fraction digits).
inline GauStr ftoa(double value, int decimals = 2)
{
    GauStr s = gau_str();
    gau_append(s, value, decimals);
    return s;
}

// Decimal text of an integer value.
inline GauStr itoa(long value)
{
    GauStr s = gau_str();
    gau_append(s, value);
    return s;
}

struct Vector3f
{
    float x;
    float y;
    float z;
};

// Reads 3 consecutive input pins starting at baseIndex.
inline Vector3f gau_read_Vector3f(int baseIndex)
{
    Vector3f value;
    value.x = static_cast<float>(gau_input_f64(baseIndex + 0));
    value.y = static_cast<float>(gau_input_f64(baseIndex + 1));
    value.z = static_cast<float>(gau_input_f64(baseIndex + 2));
    return value;
}

// Writes 3 consecutive output pins starting at baseIndex.
inline void gau_write_Vector3f(int baseIndex, const Vector3f& value)
{
    gau_output_f64(baseIndex + 0, static_cast<double>(value.x));
    gau_output_f64(baseIndex + 1, static_cast<double>(value.y));
    gau_output_f64(baseIndex + 2, static_cast<double>(value.z));
}
